# Generated by Django 5.2.17 on 2026-08-30 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0002_gateway_company"),
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisualizationTab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date Updated"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                ("code", models.CharField(max_length=64, verbose_name="Code")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort Order"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visualization_tabs",
                        to="device.devicetype",
                        verbose_name="Device Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visualization Tab",
                "verbose_name_plural": "Visualization Tabs",
                "ordering": ("sort_order", "title", "pk"),
            },
        ),
        migrations.CreateModel(
            name="Visualization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date Updated"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "chart_type",
                    models.CharField(
                        choices=[("line", "Line"), ("bar", "Bar"), ("area", "Area")],
                        default="line",
                        max_length=16,
                        verbose_name="Chart Type",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort Order"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "x_axis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="x_axis_visualizations",
                        to="device.parameterdefinition",
                        verbose_name="X Axis Parameter",
                    ),
                ),
                (
                    "y_axis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="y_axis_visualizations",
                        to="device.parameterdefinition",
                        verbose_name="Y Axis Parameter",
                    ),
                ),
                (
                    "tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visualizations",
                        to="event.visualizationtab",
                        verbose_name="Tab",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visualization",
                "verbose_name_plural": "Visualizations",
                "ordering": ("sort_order", "title", "pk"),
            },
        ),
        migrations.AddConstraint(
            model_name="visualizationtab",
            constraint=models.UniqueConstraint(
                fields=("device_type", "code"),
                name="uniq_visualization_tab_device_code",
            ),
        ),
    ]
