# Generated by Django 5.2.17 on 2026-08-24 14:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date Updated"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=64, unique=True, verbose_name="Code"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
            ],
            options={
                "verbose_name": "Event Type",
                "verbose_name_plural": "Event Types",
            },
        ),
        migrations.CreateModel(
            name="PayloadSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date Updated"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="Version")),
                (
                    "encoding",
                    models.CharField(
                        default="utf-8",
                        editable=False,
                        max_length=16,
                        verbose_name="Encoding",
                    ),
                ),
                (
                    "expected_length",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Expected Length"
                    ),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payload_schemas",
                        to="device.devicetype",
                        verbose_name="Device Type",
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payload_schemas",
                        to="event.eventtype",
                        verbose_name="Event Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payload Schema",
                "verbose_name_plural": "Payload Schemas",
            },
        ),
        migrations.CreateModel(
            name="PayloadField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date Updated"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                ("code", models.CharField(max_length=64, verbose_name="Code")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("start_byte", models.PositiveIntegerField(verbose_name="Start Byte")),
                ("end_byte", models.PositiveIntegerField(verbose_name="End Byte")),
                (
                    "wire_codec",
                    models.CharField(
                        choices=[
                            ("integer", "Integer"),
                            ("utf8", "UTF-8 String"),
                            ("boolean", "Boolean"),
                        ],
                        max_length=16,
                        verbose_name="Wire Codec",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("metric", "Metric"),
                            ("timestamp", "Timestamp"),
                            ("sequence", "Sequence"),
                            ("checksum", "Checksum"),
                        ],
                        default="metric",
                        max_length=16,
                        verbose_name="Role",
                    ),
                ),
                (
                    "payload_schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="event.payloadschema",
                        verbose_name="Payload Schema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payload Field",
                "verbose_name_plural": "Payload Fields",
            },
        ),
        migrations.CreateModel(
            name="ProjectionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date Updated"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[("field", "Payload Field"), ("constant", "Constant")],
                        max_length=16,
                        verbose_name="Source Kind",
                    ),
                ),
                (
                    "constant_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Constant Value"
                    ),
                ),
                (
                    "conversion_config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Conversion Config"
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projection_rules",
                        to="device.parameterdefinition",
                        verbose_name="Parameter",
                    ),
                ),
                (
                    "payload_schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projection_rules",
                        to="event.payloadschema",
                        verbose_name="Payload Schema",
                    ),
                ),
                (
                    "source_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projection_rules",
                        to="event.payloadfield",
                        verbose_name="Source Field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projection Rule",
                "verbose_name_plural": "Projection Rules",
            },
        ),
        migrations.CreateModel(
            name="RawEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "received_gateway_uid",
                    models.CharField(
                        max_length=64, verbose_name="Received Gateway UID"
                    ),
                ),
                (
                    "received_local_id",
                    models.CharField(max_length=64, verbose_name="Received Local ID"),
                ),
                (
                    "received_schema_version",
                    models.PositiveIntegerField(verbose_name="Received Schema Version"),
                ),
                (
                    "raw_payload",
                    models.TextField(blank=True, verbose_name="Raw Payload"),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Received At"),
                ),
                (
                    "device_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Device Timestamp"
                    ),
                ),
                (
                    "message_id",
                    models.CharField(max_length=128, verbose_name="Message ID"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "parsing_error",
                    models.TextField(blank=True, verbose_name="Parsing Error"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raw_events",
                        to="device.device",
                        verbose_name="Device",
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raw_events",
                        to="event.eventtype",
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raw_events",
                        to="device.gateway",
                        verbose_name="Gateway",
                    ),
                ),
                (
                    "payload_schema",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raw_events",
                        to="event.payloadschema",
                        verbose_name="Payload Schema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raw Event",
                "verbose_name_plural": "Raw Events",
            },
        ),
        migrations.CreateModel(
            name="ParameterReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observed_at", models.DateTimeField(verbose_name="Observed At")),
                (
                    "integer_value",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Integer Value"
                    ),
                ),
                (
                    "datetime_value",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Datetime Value"
                    ),
                ),
                (
                    "string_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="String Value"
                    ),
                ),
                (
                    "boolean_value",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Boolean Value"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parameter_readings",
                        to="device.device",
                        verbose_name="Device",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readings",
                        to="device.parameterdefinition",
                        verbose_name="Parameter",
                    ),
                ),
                (
                    "projection_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parameter_readings",
                        to="event.projectionrule",
                        verbose_name="Projection Rule",
                    ),
                ),
                (
                    "raw_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parameter_readings",
                        to="event.rawevent",
                        verbose_name="Raw Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parameter Reading",
                "verbose_name_plural": "Parameter Readings",
            },
        ),
        migrations.AddConstraint(
            model_name="payloadschema",
            constraint=models.UniqueConstraint(
                fields=("event_type", "device_type", "version"),
                name="uniq_event_device_schema_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="payloadschema",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expected_length__isnull", True),
                    ("expected_length__gt", 0),
                    _connector="OR",
                ),
                name="schema_expected_length_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="payloadschema",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)), name="schema_version_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="payloadschema",
            constraint=models.CheckConstraint(
                condition=models.Q(("encoding", "utf-8")), name="schema_encoding_utf8"
            ),
        ),
        migrations.AddConstraint(
            model_name="payloadfield",
            constraint=models.UniqueConstraint(
                fields=("payload_schema", "code"), name="uniq_schema_payload_field_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="payloadfield",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "timestamp")),
                fields=("payload_schema",),
                name="uniq_schema_timestamp_field",
            ),
        ),
        migrations.AddConstraint(
            model_name="payloadfield",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_byte__gt", models.F("start_byte"))),
                name="payload_field_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectionrule",
            constraint=models.UniqueConstraint(
                fields=("payload_schema", "parameter"),
                name="uniq_schema_parameter_projection",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectionrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("constant_value__isnull", True),
                        ("source_field__isnull", False),
                        ("source_kind", "field"),
                    ),
                    models.Q(
                        ("constant_value__isnull", False),
                        ("source_field__isnull", True),
                        ("source_kind", "constant"),
                    ),
                    _connector="OR",
                ),
                name="projection_has_one_source",
            ),
        ),
        migrations.AddIndex(
            model_name="rawevent",
            index=models.Index(
                fields=["gateway", "-received_at"], name="raw_gateway_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawevent",
            index=models.Index(
                fields=["status", "received_at"], name="raw_status_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rawevent",
            constraint=models.UniqueConstraint(
                fields=("gateway", "message_id"), name="uniq_gateway_message_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="rawevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("received_schema_version__gt", 0)),
                name="raw_schema_version_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="parameterreading",
            index=models.Index(
                fields=["device", "parameter", "-observed_at"],
                name="reading_device_param_time_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="parameterreading",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("integer_value__isnull", False),
                        ("datetime_value__isnull", True),
                        ("string_value__isnull", True),
                        ("boolean_value__isnull", True),
                    ),
                    models.Q(
                        ("integer_value__isnull", True),
                        ("datetime_value__isnull", False),
                        ("string_value__isnull", True),
                        ("boolean_value__isnull", True),
                    ),
                    models.Q(
                        ("integer_value__isnull", True),
                        ("datetime_value__isnull", True),
                        ("string_value__isnull", False),
                        ("boolean_value__isnull", True),
                    ),
                    models.Q(
                        ("integer_value__isnull", True),
                        ("datetime_value__isnull", True),
                        ("string_value__isnull", True),
                        ("boolean_value__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="reading_has_one_typed_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="parameterreading",
            constraint=models.UniqueConstraint(
                fields=("raw_event", "device", "parameter"),
                name="uniq_event_device_parameter_reading",
            ),
        ),
    ]
