# Generated by Django 5.2.17 on 2026-08-24 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date Updated"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=64, unique=True, verbose_name="Code"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
            ],
            options={
                "verbose_name": "Device Type",
                "verbose_name_plural": "Device Types",
            },
        ),
        migrations.CreateModel(
            name="Gateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date Updated"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "uid",
                    models.CharField(max_length=64, unique=True, verbose_name="UID"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Gateway",
                "verbose_name_plural": "Gateways",
            },
        ),
        migrations.CreateModel(
            name="ParameterDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date Updated"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=64, unique=True, verbose_name="Code"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("integer", "Integer"),
                            ("datetime", "Datetime"),
                            ("string", "String"),
                            ("boolean", "Boolean"),
                        ],
                        max_length=16,
                        verbose_name="Value Type",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Unit"
                    ),
                ),
            ],
            options={
                "verbose_name": "Parameter Definition",
                "verbose_name_plural": "Parameter Definitions",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date Updated"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                ("local_id", models.CharField(max_length=64, verbose_name="Local ID")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="device.devicetype",
                        verbose_name="Device Type",
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="device.gateway",
                        verbose_name="Gateway",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("gateway", "local_id"), name="uniq_gateway_local_device"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceTypeParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date Updated"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parameter_assignments",
                        to="device.devicetype",
                        verbose_name="Device Type",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_type_assignments",
                        to="device.parameterdefinition",
                        verbose_name="Parameter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Type Parameter",
                "verbose_name_plural": "Device Type Parameters",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device_type", "parameter"),
                        name="uniq_device_type_parameter",
                    )
                ],
            },
        ),
    ]
