# Generated by Django 5.2.17 on 2026-08-26 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_company"),
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gateways",
                to="account.company",
                verbose_name="Company",
            ),
        ),
    ]
