# Generated by Django 5.2.17 on 2026-09-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0002_gateway_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway",
            name="ingest_token_hash",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=128,
                verbose_name="Ingest Token Hash",
            ),
        ),
    ]
